default_language_version:
  python: python3.11
default_stages:
- commit
exclude: ^docs/|/migrations/|.conf.py|migrations|.git|.tox
fail_fast: true
repos:
- hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-ast
  - id: check-json
  - id: check-toml
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: check-builtin-literals
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-docstring-first
  - id: check-added-large-files
  - id: detect-private-key
  - args:
    - --allow-missing-credentials
    id: detect-aws-credentials
  - args:
    - --autofix
    id: pretty-format-json
  - id: requirements-txt-fixer
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
- hooks:
  - args:
    - --target-version
    - '4.2'
    id: django-upgrade
  repo: https://github.com/adamchainz/django-upgrade
  rev: 1.15.0
- hooks:
  - args:
    - --fix
    - --exit-non-zero-on-fix
    id: ruff
  - id: ruff-format
  repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.1
- hooks:
  - id: commitizen
  - id: commitizen-branch
    stages:
    - push
  repo: https://github.com/commitizen-tools/commitizen
  rev: 3.12.0
